# Essential Imports and Configurations

In [1]:
import pandas as pd
import sqlalchemy as sqla
import os
import re

from datetime import datetime
from pathlib import Path
from sqlalchemy import create_engine, text

from dotenv import load_dotenv
from typing import Dict, Optional

In [2]:
load_dotenv()

user: str = os.getenv("DB_USER")
password: str = os.getenv("DB_PASSWORD")
host: str = os.getenv("DB_HOST")
port: str = os.getenv("PORT")
database: str = os.getenv("DB_NAME")

In [3]:
pd.set_option('display.max_rows', None)      # Show all rows
pd.set_option('display.max_columns', None)   # Show all columns
pd.set_option('display.width', 1000)         # Prevents wrapping

In [4]:
def get_connection() -> sqla.Engine:
    engine: sqla.Engine = create_engine(
        f"postgresql://{user}:{password}@{host}:{port}/{database}"
    )
    return engine

try:
    engine: sqla.Engine = get_connection()
    print(f"Connection to the {host} for user {user} created successfully.")

except Exception as ex:
    print("Connection could not be made due to the following error:\n", ex)

Connection to the localhost for user postgres created successfully.

In [5]:
def ingest_data() -> None:
    """
    Populates the Cyber Databoard database with the CSV files data.
    """
    engine: sqla.Engine = get_connection()
    parent: str = (Path.cwd())
    path: Path = Path(f"{parent}/data/")
    day_regex: str = r"[\w\-.]+(?=-[Ww]orkingHours)"
    type_regex: str = r"(?<=-[Ww]orkingHours-)[\w\-.]+(?=.pcap)"

    for file_name in path.iterdir():
        with open(file_name, mode='r') as file:
            datafile: pd.DataFrame = pd.read_csv(file)
            day_match: re.Match = re.search(day_regex, str(file_name.name))
            type_match: re.Match = re.search(type_regex, str(file_name))
            if day_match:
                day_match: str = day_match.group().replace("_", " ")
            if type_match:
                type_match: str = type_match.group().replace("_", " ")
            else:
                type_match: str = "Working_Hours"

            table_name: str = f"{day_match}_{type_match}".replace(" ", "_")
            
            datafile.to_sql(
                f"{table_name}",
                engine, 
                if_exists="replace",
                index=False
            )

# Data Analysis

In [ ]:
def query_database(query: str, para_bindings: Optional[Dict[str, str | int]] = None) -> pd.DataFrame:
    with engine.connect() as connection:
        query: sqla.Text = text(query)

        result: sqla.CursorResult = connection.execute(query, para_bindings)
        df: pd.DataFrame = pd.DataFrame(result)
        
        return df

# Friday_DDOS Analysis

This dataset seems to contain the data from DDOS attacks that occured during Friday Afternoon.

In [7]:
Friday_DDOS: pd.DataFrame = query_database('SELECT * FROM "Friday_Afternoon_DDos"')

In [8]:
Friday_DDOS.info()

<class 'pandas.DataFrame'>
RangeIndex: 225745 entries, 0 to 225744
Data columns (total 85 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Flow ID                       225745 non-null  str
 1    Source IP                    225745 non-null  str
 2    Source Port                  225745 non-null  int64
 3    Destination IP               225745 non-null  str
 4    Destination Port             225745 non-null  int64
 5    Protocol                     225745 non-null  int64
 6    Timestamp                    225745 non-null  str
 7    Flow Duration                225745 non-null  int64
 8    Total Fwd Packets            225745 non-null  int64
 9    Total Backward Packets       225745 non-null  int64
 10  Total Length of Fwd Packets   225745 non-null  int64
 11   Total Length of Bwd Packets  225745 non-null  int64
 12   Fwd Packet Length Max        225745 non-null  int64
 13   Fwd Packet Length Min        225745 non-null  int64
 14   Fwd Packet Length Mean       225745 non-null  float64
 15   Fwd Packet Length Std        225745 non-null  float64
 16  Bwd Packet Length Max         225745 non-null  int64
 17   Bwd Packet Length Min        225745 non-null  int64
 18   Bwd Packet Length Mean       225745 non-null  float64
 19   Bwd Packet Length Std        225745 non-null  float64
 20  Flow Bytes/s                  225741 non-null  float64
 21   Flow Packets/s               225745 non-null  float64
 22   Flow IAT Mean                225745 non-null  float64
 23   Flow IAT Std                 225745 non-null  float64
 24   Flow IAT Max                 225745 non-null  int64
 25   Flow IAT Min                 225745 non-null  int64
 26  Fwd IAT Total                 225745 non-null  int64
 27   Fwd IAT Mean                 225745 non-null  float64
 28   Fwd IAT Std                  225745 non-null  float64
 29   Fwd IAT Max                  225745 non-null  int64
 30   Fwd IAT Min                  225745 non-null  int64
 31  Bwd IAT Total                 225745 non-null  int64
 32   Bwd IAT Mean                 225745 non-null  float64
 33   Bwd IAT Std                  225745 non-null  float64
 34   Bwd IAT Max                  225745 non-null  int64
 35   Bwd IAT Min                  225745 non-null  int64
 36  Fwd PSH Flags                 225745 non-null  int64
 37   Bwd PSH Flags                225745 non-null  int64
 38   Fwd URG Flags                225745 non-null  int64
 39   Bwd URG Flags                225745 non-null  int64
 40   Fwd Header Length            225745 non-null  int64
 41   Bwd Header Length            225745 non-null  int64
 42  Fwd Packets/s                 225745 non-null  float64
 43   Bwd Packets/s                225745 non-null  float64
 44   Min Packet Length            225745 non-null  int64
 45   Max Packet Length            225745 non-null  int64
 46   Packet Length Mean           225745 non-null  float64
 47   Packet Length Std            225745 non-null  float64
 48   Packet Length Variance       225745 non-null  float64
 49  FIN Flag Count                225745 non-null  int64
 50   SYN Flag Count               225745 non-null  int64
 51   RST Flag Count               225745 non-null  int64
 52   PSH Flag Count               225745 non-null  int64
 53   ACK Flag Count               225745 non-null  int64
 54   URG Flag Count               225745 non-null  int64
 55   CWE Flag Count               225745 non-null  int64
 56   ECE Flag Count               225745 non-null  int64
 57   Down/Up Ratio                225745 non-null  int64
 58   Average Packet Size          225745 non-null  float64
 59   Avg Fwd Segment Size         225745 non-null  float64
 60   Avg Bwd Segment Size         225745 non-null  float64
 61   Fwd Header Length.1          225745 non-null  int64
 62  Fwd Avg Bytes/Bulk            225745 non-null  int64
 63   Fwd Avg Packets/Bulk         225745 non-null  int64
 64   Fwd Avg Bulk Rate            225745 non-null  int64
 65   Bwd Avg Bytes/Bulk           225745 non-null  int64
 66   Bwd Avg Packets/Bulk         225745 non-null  int64
 67  Bwd Avg Bulk Rate             225745 non-null  int64
 68  Subflow Fwd Packets           225745 non-null  int64
 69   Subflow Fwd Bytes            225745 non-null  int64
 70   Subflow Bwd Packets          225745 non-null  int64
 71   Subflow Bwd Bytes            225745 non-null  int64
 72  Init_Win_bytes_forward        225745 non-null  int64
 73   Init_Win_bytes_backward      225745 non-null  int64
 74   act_data_pkt_fwd             225745 non-null  int64
 75   min_seg_size_forward         225745 non-null  int64
 76  Active Mean                   225745 non-null  float64
 77   Active Std                   225745 non-null  float64
 78   Active Max                   225745 non-null  int64
 79   Active Min                   225745 non-null  int64
 80  Idle Mean                     225745 non-null  float64
 81   Idle Std                     225745 non-null  float64
 82   Idle Max                     225745 non-null  int64
 83   Idle Min                     225745 non-null  int64
 84   Label                        225745 non-null  str
dtypes: float64(24), int64(56), str(5)
memory usage: 163.0 MB

In [9]:
Friday_DDOS.describe()

C:\Users\emera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pandas\core\nanops.py:1020: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
C:\Users\emera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pandas\core\nanops.py:1020: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,225745.000000,225745.00000,225745.000000,2.257450e+05,225745.000000,225745.000000,225745.000000,2.257450e+05,225745.000000,225745.000000,225745.000000,225745.000000,225745.000000,225745.000000,225745.000000,225745.000000,2.257410e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,225745.000000,225745.0,225745.0,225745.0,225745.000000,225745.000000,2.257450e+05,2.257450e+05,225745.000000,225745.000000,225745.000000,225745.000000,2.257450e+05,225745.000000,225745.000000,225745.000000,225745.000000,225745.000000,225745.000000,225745.0,225745.000000,225745.000000,225745.000000,225745.000000,225745.000000,225745.000000,225745.0,225745.0,225745.0,225745.0,225745.0,225745.0,225745.000000,225745.000000,225745.000000,2.257450e+05,225745.000000,225745.000000,225745.000000,225745.000000,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05,2.257450e+05
mean,38257.568402,8879.61946,7.600288,1.624165e+07,4.874916,4.572775,939.463346,5.960477e+03,538.535693,27.882221,164.826715,214.907242,2735.585147,16.718776,890.536849,1230.172938,inf,inf,1.580587e+06,4.248569e+06,1.348977e+07,2.811855e+04,1.539652e+07,2.540610e+06,5.195207e+06,1.299434e+07,2.073698e+05,6.564701e+06,9.476322e+05,1.610306e+06,4.567514e+06,2.257817e+05,0.033223,0.0,0.0,0.0,111.522718,106.789023,1.261508e+04,1.641693e+03,8.072595,3226.045339,515.002137,1085.593207,2.789906e+06,0.002671,0.033223,0.000120,0.351162,0.504463,0.140752,0.0,0.000120,1.005821,574.568843,164.826715,890.536849,111.522718,0.0,0.0,0.0,0.0,0.0,0.0,4.874916,939.463346,4.572775,5.960477e+03,4247.436922,601.048635,3.311497,21.482753,1.848261e+05,1.293436e+04,2.080849e+05,1.776201e+05,1.032214e+07,3.611943e+06,1.287813e+07,7.755355e+06
std,23057.302075,19754.64740,3.881586,3.152437e+07,15.422874,21.755356,3249.403484,3.921834e+04,1864.128991,163.324159,504.892965,797.411073,3705.123460,50.480568,1120.324921,1733.201267,NaN,NaN,2.701596e+06,7.622819e+06,2.670172e+07,7.598100e+05,3.160826e+07,5.934694e+06,1.078635e+07,2.748870e+07,3.795228e+06,2.198455e+07,4.586374e+06,5.475778e+06,1.617865e+07,4.019290e+06,0.179220,0.0,0.0,0.0,375.790727,511.765795,1.106701e+05,1.989593e+04,15.767713,3813.134850,559.064495,1269.558714,4.115941e+06,0.051614,0.179220,0.010936,0.477334,0.499981,0.347766,0.0,0.010936,1.430781,626.096202,504.892965,1120.324921,375.790727,0.0,0.0,0.0,0.0,0.0,0.0,15.422874,3249.403484,21.755356,3.921834e+04,8037.781019,4319.720339,12.270018,4.166799,7.979250e+05,2.102737e+05,9.002350e+05,7.842602e+05,2.185303e+07,1.275689e+07,2.692126e+07,1.983109e+07
min,0.000000,0.00000,0.000000,-1.000000e+00,1.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.200000e+07,-2.000000e+06,-1.000000e+00,0.000000e+00,-1.000000e+00,-1.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,0.000000,0.000000e+00,-1.000000,-1.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,18990.000000,80.00000,6.000000,7.118000e+04,2.000000,1.000000,26.000000,0.000000e+00,6.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.209087e+01,6.185506e-01,1.918162e+04,1.910446e+04,6.117800e+04,1.000000e+00,1.290000e+02,1.100000e+02,0.000000e+00,1.240000e+02,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0,64.000000,20.000000,4.246842e-01,3.527347e-02,0.000000,6.000000,6.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,7.500000,6.000000,0.000000,64.000000,0.0,0.0,0.0,0.0,0.0,0.0,2.000000,26.000000,1.000000,0.000000e+00,229.000000,-1.000000,1.000000,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,49799.000000,80.00000,6.000000,1.452333e+06,3.000000,4.000000,30.000000,1.640000e+02,20.000000,0.000000,8.666667,5.301991,99.000000,0.000000,92.000000,2.449490,1.136606e+03,5.179323e+00,2.245169e+05,5.641676e+05,1.422624e+06,3.000000e+00,2.371000e+04,1.032933e+04,1.273499e+04,2.302800e+04,4.000000e+00,4.110100e+04,1.000940e+04,1.470372e+04,3.336500e+04,3.000000e+00,0.000000,0.0,0.0,0.0,72.000000,92.000000,2.315615e+00,1.483290e+00,0.000000,513.000000,110.333333,154.030812,2.372549e+04,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.000000,1.000000,141.000000,8.666667,92.000000,72.000000,0.0,0.0,0.0,0.0,0.0,0.0,3.000000,30.000000,4.000000,1.640000e+02,256.000000,126.000000,2.000000,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,58296.000000,80.00000,6.000000,8.805237e+06,5.000000,5.000000,63.000000,1.160100e+04,34.000000,6.000000,32.000000,10.263203,5840.000000,6.000000,1934.500000,2436.833027,2.159723e+04,7.046933e+01,2.013459e+06,4.033232e+06,8.358910e+06,3.900000e+01,7.869855e+06,2.017643e+06,3.680321e+06,7.548056e+06,1.220000e+02,1.111677e+06,2.655838e+05,5.177920e+05,1.094045e+06,4.700000e+01,0.000000,0.0,0.0,0.0,100.000000,120.000000,3.287275e+01,2.102475e+01,6.000000,5840.000000,1162.700000,2131.870960,4.544874e+06,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.0,0.000000,1.000000,1291.888889,32.000000,1934.500000,100.000000,0.0,0.0,0.0,0.0,0.0,0.0,5.000000,63.000000,5.000000,1.160100e+04,8192.000000,229.000000,4.000000,20.000000,1.878000e+03,0.000000e+00,1.878000e+03,1.862000e+03,8.239725e+06,0.000000e+00,8.253838e+06,7.422849e+06
max,65534.000000,65532.00000,17.000000,1.199999e+08,1932.000000,2942.000000,183012.000000,5.172346e+06,11680.000000,1472.000000,3867.000000,6692.644993,11680.000000,1460.000000,5800.500000,8194.660487,inf,inf,1.070000e+08,6.920000e+07,1.200000e+08,1.070000e+08,1.200000e+08,1.200000e+08,7.670000e+07,1.200000e+08,1.200000e+08,1.200000e+08,1.200000e+08,7.670000e+07,1.200000e+08,1.200000e+08,1.000000,0.0,0.0,0.0,39396.000000,58852.000000,3.000000e+06,2.000000e+06,337.000000,11680.000000,1936.833333,4731.522394,2.240000e+07,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,7.000000,2528.000000,3867.000000,5800.500000,39396.000000,0.0,0.0,0.0,0.0,0.0,0.0,1932.000000,183012.000000,2942.000000,5.172346e+06,65535.000000,65535.000000,1931.000000,52.000000,1.000000e+08,3.950000e+07,1.000000e+08,1.000000e+08,1.200000e+08,6.530000e+07,1.200000e+08,1.200000e+08

In [10]:
Friday_DDOS.isnull().any()

# Only Flow Bytes have null values

Flow ID                         False
 Source IP                      False
 Source Port                    False
 Destination IP                 False
 Destination Port               False
 Protocol                       False
 Timestamp                      False
 Flow Duration                  False
 Total Fwd Packets              False
 Total Backward Packets         False
Total Length of Fwd Packets     False
 Total Length of Bwd Packets    False
 Fwd Packet Length Max          False
 Fwd Packet Length Min          False
 Fwd Packet Length Mean         False
 Fwd Packet Length Std          False
Bwd Packet Length Max           False
 Bwd Packet Length Min          False
 Bwd Packet Length Mean         False
 Bwd Packet Length Std          False
Flow Bytes/s                     True
 Flow Packets/s                 False
 Flow IAT Mean                  False
 Flow IAT Std                   False
 Flow IAT Max                   False
 Flow IAT Min                   False
Fwd IAT Total                   False
 Fwd IAT Mean                   False
 Fwd IAT Std                    False
 Fwd IAT Max                    False
 Fwd IAT Min                    False
Bwd IAT Total                   False
 Bwd IAT Mean                   False
 Bwd IAT Std                    False
 Bwd IAT Max                    False
 Bwd IAT Min                    False
Fwd PSH Flags                   False
 Bwd PSH Flags                  False
 Fwd URG Flags                  False
 Bwd URG Flags                  False
 Fwd Header Length              False
 Bwd Header Length              False
Fwd Packets/s                   False
 Bwd Packets/s                  False
 Min Packet Length              False
 Max Packet Length              False
 Packet Length Mean             False
 Packet Length Std              False
 Packet Length Variance         False
FIN Flag Count                  False
 SYN Flag Count                 False
 RST Flag Count                 False
 PSH Flag Count                 False
 ACK Flag Count                 False
 URG Flag Count                 False
 CWE Flag Count                 False
 ECE Flag Count                 False
 Down/Up Ratio                  False
 Average Packet Size            False
 Avg Fwd Segment Size           False
 Avg Bwd Segment Size           False
 Fwd Header Length.1            False
Fwd Avg Bytes/Bulk              False
 Fwd Avg Packets/Bulk           False
 Fwd Avg Bulk Rate              False
 Bwd Avg Bytes/Bulk             False
 Bwd Avg Packets/Bulk           False
Bwd Avg Bulk Rate               False
Subflow Fwd Packets             False
 Subflow Fwd Bytes              False
 Subflow Bwd Packets            False
 Subflow Bwd Bytes              False
Init_Win_bytes_forward          False
 Init_Win_bytes_backward        False
 act_data_pkt_fwd               False
 min_seg_size_forward           False
Active Mean                     False
 Active Std                     False
 Active Max                     False
 Active Min                     False
Idle Mean                       False
 Idle Std                       False
 Idle Max                       False
 Idle Min                       False
 Label                          False
dtype: bool

In [11]:
Friday_DDOS['Flow Bytes/s'].isnull().sum()

np.int64(4)

In [12]:
# Since there are so little missing values, we can just drop them

print(f"Before removing missing values: {Friday_DDOS.shape}")
Friday_DDOS.dropna(inplace=True)
print(f"After removing missing values: {Friday_DDOS.shape}")

Before removing missing values: (225745, 85)
After removing missing values: (225741, 85)

In [13]:
str_col  = Friday_DDOS.select_dtypes(include='str')
print(str_col.columns)

# We are going to have to handle all these non-string columns expect Label for ML 
# Timestamp can be converted to date format but everything else will need to be encoded as values represent IP addresses.

Index(['Flow ID', ' Source IP', ' Destination IP', ' Timestamp', ' Label'], dtype='str')

In [14]:
Friday_DDOS[' Timestamp'] = pd.to_datetime(Friday_DDOS[' Timestamp'], format="%d/%m/%Y %H:%M")

Friday_DDOS.info()

<class 'pandas.DataFrame'>
Index: 225741 entries, 0 to 225744
Data columns (total 85 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Flow ID                       225741 non-null  str
 1    Source IP                    225741 non-null  str
 2    Source Port                  225741 non-null  int64
 3    Destination IP               225741 non-null  str
 4    Destination Port             225741 non-null  int64
 5    Protocol                     225741 non-null  int64
 6    Timestamp                    225741 non-null  datetime64[us]
 7    Flow Duration                225741 non-null  int64
 8    Total Fwd Packets            225741 non-null  int64
 9    Total Backward Packets       225741 non-null  int64
 10  Total Length of Fwd Packets   225741 non-null  int64
 11   Total Length of Bwd Packets  225741 non-null  int64
 12   Fwd Packet Length Max        225741 non-null  int64
 13   Fwd Packet Length Min        225741 non-null  int64
 14   Fwd Packet Length Mean       225741 non-null  float64
 15   Fwd Packet Length Std        225741 non-null  float64
 16  Bwd Packet Length Max         225741 non-null  int64
 17   Bwd Packet Length Min        225741 non-null  int64
 18   Bwd Packet Length Mean       225741 non-null  float64
 19   Bwd Packet Length Std        225741 non-null  float64
 20  Flow Bytes/s                  225741 non-null  float64
 21   Flow Packets/s               225741 non-null  float64
 22   Flow IAT Mean                225741 non-null  float64
 23   Flow IAT Std                 225741 non-null  float64
 24   Flow IAT Max                 225741 non-null  int64
 25   Flow IAT Min                 225741 non-null  int64
 26  Fwd IAT Total                 225741 non-null  int64
 27   Fwd IAT Mean                 225741 non-null  float64
 28   Fwd IAT Std                  225741 non-null  float64
 29   Fwd IAT Max                  225741 non-null  int64
 30   Fwd IAT Min                  225741 non-null  int64
 31  Bwd IAT Total                 225741 non-null  int64
 32   Bwd IAT Mean                 225741 non-null  float64
 33   Bwd IAT Std                  225741 non-null  float64
 34   Bwd IAT Max                  225741 non-null  int64
 35   Bwd IAT Min                  225741 non-null  int64
 36  Fwd PSH Flags                 225741 non-null  int64
 37   Bwd PSH Flags                225741 non-null  int64
 38   Fwd URG Flags                225741 non-null  int64
 39   Bwd URG Flags                225741 non-null  int64
 40   Fwd Header Length            225741 non-null  int64
 41   Bwd Header Length            225741 non-null  int64
 42  Fwd Packets/s                 225741 non-null  float64
 43   Bwd Packets/s                225741 non-null  float64
 44   Min Packet Length            225741 non-null  int64
 45   Max Packet Length            225741 non-null  int64
 46   Packet Length Mean           225741 non-null  float64
 47   Packet Length Std            225741 non-null  float64
 48   Packet Length Variance       225741 non-null  float64
 49  FIN Flag Count                225741 non-null  int64
 50   SYN Flag Count               225741 non-null  int64
 51   RST Flag Count               225741 non-null  int64
 52   PSH Flag Count               225741 non-null  int64
 53   ACK Flag Count               225741 non-null  int64
 54   URG Flag Count               225741 non-null  int64
 55   CWE Flag Count               225741 non-null  int64
 56   ECE Flag Count               225741 non-null  int64
 57   Down/Up Ratio                225741 non-null  int64
 58   Average Packet Size          225741 non-null  float64
 59   Avg Fwd Segment Size         225741 non-null  float64
 60   Avg Bwd Segment Size         225741 non-null  float64
 61   Fwd Header Length.1          225741 non-null  int64
 62  Fwd Avg Bytes/Bulk            225741 non-null  int64
 63   Fwd Avg Packets/Bulk         225741 non-null  int64
 64   Fwd Avg Bulk Rate            225741 non-null  int64
 65   Bwd Avg Bytes/Bulk           225741 non-null  int64
 66   Bwd Avg Packets/Bulk         225741 non-null  int64
 67  Bwd Avg Bulk Rate             225741 non-null  int64
 68  Subflow Fwd Packets           225741 non-null  int64
 69   Subflow Fwd Bytes            225741 non-null  int64
 70   Subflow Bwd Packets          225741 non-null  int64
 71   Subflow Bwd Bytes            225741 non-null  int64
 72  Init_Win_bytes_forward        225741 non-null  int64
 73   Init_Win_bytes_backward      225741 non-null  int64
 74   act_data_pkt_fwd             225741 non-null  int64
 75   min_seg_size_forward         225741 non-null  int64
 76  Active Mean                   225741 non-null  float64
 77   Active Std                   225741 non-null  float64
 78   Active Max                   225741 non-null  int64
 79   Active Min                   225741 non-null  int64
 80  Idle Mean                     225741 non-null  float64
 81   Idle Std                     225741 non-null  float64
 82   Idle Max                     225741 non-null  int64
 83   Idle Min                     225741 non-null  int64
 84   Label                        225741 non-null  str
dtypes: datetime64[us](1), float64(24), int64(56), str(4)
memory usage: 162.1 MB

1. What are the most common ports used here?

In [15]:
ports = query_database('SELECT " Destination Port", " Label", COUNT(*) AS total FROM "Friday_Afternoon_DDos" GROUP BY  " Destination Port", " Label" ORDER BY COUNT(*) DESC')

In [16]:
ports.head(15)

# Here we can see that all DDoS attacks use port 80

     Destination Port   Label   total
0                  80    DDoS  128024
1                  53  BENIGN   31950
2                 443  BENIGN   13485
3                  80  BENIGN    8927
4                8080  BENIGN     510
5                 123  BENIGN     362
6                  22  BENIGN     342
7                 137  BENIGN     274
8                 389  BENIGN     261
9                  88  BENIGN     173
10                 21  BENIGN     167
11                465  BENIGN     147
12                139  BENIGN     100
13               3268  BENIGN      91
14                  0  BENIGN      54

### 2. What does the average packet size look like?
Answer: Results vary drastically but we can see that most packets are around 7.5.

In [1]:
packet_size = query_database('''SELECT " Average Packet Size", " Label", COUNT(*) AS total FROM "Friday_Afternoon_DDos" GROUP BY  " Average Packet Size", " Label" ORDER BY total DESC''')
packet_size.head(15)

NameError: name 'query_database' is not defined

In [18]:
#Thought packet size might indicate an attack. 
#Sorting by Packet size instead
packet_size = query_database('''SELECT " Average Packet Size", " Label", COUNT(*) AS total FROM "Friday_Afternoon_DDos" GROUP BY  " Average Packet Size", " Label" ORDER BY " Average Packet Size" DESC''')
packet_size.head(15)

#Turns out size is not an indication of malicious packets after all.

     Average Packet Size   Label  total
0            2528.000000  BENIGN      1
1            2357.000000  BENIGN      1
2            2324.200000    DDoS      5
3            2324.200000  BENIGN      1
4            2068.000000  BENIGN     30
5            1937.833333    DDoS    244
6            1937.833333  BENIGN     24
7            1936.833333  BENIGN     30
8            1936.833333    DDoS    233
9            1661.857143  BENIGN    581
10           1661.857143    DDoS   6053
11           1661.000000  BENIGN    753
12           1661.000000    DDoS   8605
13           1660.142857  BENIGN     29
14           1660.142857    DDoS    238

### 3. What are the most common protocols?
Answer:
1. Protocol 6 = TCP 
2. Protocol 17 = UDP 
3. Protocol 0 = N/A

In [19]:
protocols = query_database('SELECT " Protocol", " Label", COUNT(*) AS total FROM "Friday_Afternoon_DDos" GROUP BY  " Protocol", " Label" ORDER BY total DESC')
protocols
#DDoS attacks seem to use TCP

    Protocol   Label   total
0          6    DDoS  128027
1          6  BENIGN   64793
2         17  BENIGN   32871
3          0  BENIGN      54

### 4. How many DDoS attacks where there total, Friday Afternoon?
Answer: 128,027

In [20]:
num_attacks = query_database('SELECT " Label", COUNT(*) AS total FROM "Friday_Afternoon_DDos" GROUP BY " Label" ORDER BY total DESC')
num_attacks

    Label   total
0    DDoS  128027
1  BENIGN   97718

In [25]:
Friday_DDOS[' Label'].unique()

<ArrowStringArray>
['BENIGN', 'DDoS']
Length: 2, dtype: str

### 5. What time did each attack take place at?
Answer: The attack seemed to occur from 3:57pm to 4:16pm

In [30]:
times = query_database('SELECT " Timestamp", COUNT(*) AS total FROM "Friday_Afternoon_DDos" WHERE " Label" =  \'DDoS\'  GROUP BY " Timestamp" ORDER BY total DESC')
times

        Timestamp  total
0   7/7/2017 3:57   8244
1   7/7/2017 4:01   6977
2   7/7/2017 4:02   6889
3   7/7/2017 4:03   6778
4   7/7/2017 3:59   6607
5   7/7/2017 3:58   6576
6   7/7/2017 4:12   6552
7   7/7/2017 4:00   6533
8   7/7/2017 4:09   6466
9   7/7/2017 4:14   6435
10  7/7/2017 4:13   6403
11  7/7/2017 4:04   6364
12  7/7/2017 4:08   6305
13  7/7/2017 4:11   6300
14  7/7/2017 4:05   6273
15  7/7/2017 4:15   6265
16  7/7/2017 4:10   6264
17  7/7/2017 4:07   6053
18  7/7/2017 4:06   5957
19  7/7/2017 3:56   2438
20  7/7/2017 4:16   1348

# Friday_PortScan Analysis

In [32]:
Friday_PS: pd.DataFrame = query_database('SELECT * FROM "Friday_Afternoon_PortScan"')

In [ ]:
Friday_PS.info()

#Exact same as the Friday_DDoS information, we only have to address the date time

<class 'pandas.DataFrame'>
RangeIndex: 286467 entries, 0 to 286466
Data columns (total 85 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Flow ID                       286467 non-null  str
 1    Source IP                    286467 non-null  str
 2    Source Port                  286467 non-null  int64
 3    Destination IP               286467 non-null  str
 4    Destination Port             286467 non-null  int64
 5    Protocol                     286467 non-null  int64
 6    Timestamp                    286467 non-null  str
 7    Flow Duration                286467 non-null  int64
 8    Total Fwd Packets            286467 non-null  int64
 9    Total Backward Packets       286467 non-null  int64
 10  Total Length of Fwd Packets   286467 non-null  int64
 11   Total Length of Bwd Packets  286467 non-null  int64
 12   Fwd Packet Length Max        286467 non-null  int64
 13   Fwd Packet Length Min        286467 non-null  int64
 14   Fwd Packet Length Mean       286467 non-null  float64
 15   Fwd Packet Length Std        286467 non-null  float64
 16  Bwd Packet Length Max         286467 non-null  int64
 17   Bwd Packet Length Min        286467 non-null  int64
 18   Bwd Packet Length Mean       286467 non-null  float64
 19   Bwd Packet Length Std        286467 non-null  float64
 20  Flow Bytes/s                  286452 non-null  float64
 21   Flow Packets/s               286467 non-null  float64
 22   Flow IAT Mean                286467 non-null  float64
 23   Flow IAT Std                 286467 non-null  float64
 24   Flow IAT Max                 286467 non-null  float64
 25   Flow IAT Min                 286467 non-null  float64
 26  Fwd IAT Total                 286467 non-null  float64
 27   Fwd IAT Mean                 286467 non-null  float64
 28   Fwd IAT Std                  286467 non-null  float64
 29   Fwd IAT Max                  286467 non-null  float64
 30   Fwd IAT Min                  286467 non-null  float64
 31  Bwd IAT Total                 286467 non-null  float64
 32   Bwd IAT Mean                 286467 non-null  float64
 33   Bwd IAT Std                  286467 non-null  float64
 34   Bwd IAT Max                  286467 non-null  float64
 35   Bwd IAT Min                  286467 non-null  float64
 36  Fwd PSH Flags                 286467 non-null  int64
 37   Bwd PSH Flags                286467 non-null  int64
 38   Fwd URG Flags                286467 non-null  int64
 39   Bwd URG Flags                286467 non-null  int64
 40   Fwd Header Length            286467 non-null  int64
 41   Bwd Header Length            286467 non-null  int64
 42  Fwd Packets/s                 286467 non-null  float64
 43   Bwd Packets/s                286467 non-null  float64
 44   Min Packet Length            286467 non-null  int64
 45   Max Packet Length            286467 non-null  int64
 46   Packet Length Mean           286467 non-null  float64
 47   Packet Length Std            286467 non-null  float64
 48   Packet Length Variance       286467 non-null  float64
 49  FIN Flag Count                286467 non-null  int64
 50   SYN Flag Count               286467 non-null  int64
 51   RST Flag Count               286467 non-null  int64
 52   PSH Flag Count               286467 non-null  int64
 53   ACK Flag Count               286467 non-null  int64
 54   URG Flag Count               286467 non-null  int64
 55   CWE Flag Count               286467 non-null  int64
 56   ECE Flag Count               286467 non-null  int64
 57   Down/Up Ratio                286467 non-null  int64
 58   Average Packet Size          286467 non-null  float64
 59   Avg Fwd Segment Size         286467 non-null  float64
 60   Avg Bwd Segment Size         286467 non-null  float64
 61   Fwd Header Length.1          286467 non-null  int64
 62  Fwd Avg Bytes/Bulk            286467 non-null  int64
 63   Fwd Avg Packets/Bulk         286467 non-null  int64
 64   Fwd Avg Bulk Rate            286467 non-null  int64
 65   Bwd Avg Bytes/Bulk           286467 non-null  int64
 66   Bwd Avg Packets/Bulk         286467 non-null  int64
 67  Bwd Avg Bulk Rate             286467 non-null  int64
 68  Subflow Fwd Packets           286467 non-null  int64
 69   Subflow Fwd Bytes            286467 non-null  int64
 70   Subflow Bwd Packets          286467 non-null  int64
 71   Subflow Bwd Bytes            286467 non-null  int64
 72  Init_Win_bytes_forward        286467 non-null  int64
 73   Init_Win_bytes_backward      286467 non-null  int64
 74   act_data_pkt_fwd             286467 non-null  int64
 75   min_seg_size_forward         286467 non-null  int64
 76  Active Mean                   286467 non-null  float64
 77   Active Std                   286467 non-null  float64
 78   Active Max                   286467 non-null  float64
 79   Active Min                   286467 non-null  float64
 80  Idle Mean                     286467 non-null  float64
 81   Idle Std                     286467 non-null  float64
 82   Idle Max                     286467 non-null  float64
 83   Idle Min                     286467 non-null  float64
 84   Label                        286467 non-null  str
dtypes: float64(36), int64(44), str(5)
memory usage: 208.0 MB

In [34]:
Friday_PS.describe()

C:\Users\emera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pandas\core\nanops.py:1020: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
C:\Users\emera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pandas\core\nanops.py:1020: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,286467.000000,286467.000000,286467.000000,2.864670e+05,286467.000000,286467.000000,286467.000000,2.864670e+05,286467.000000,286467.000000,286467.000000,286467.000000,286467.000000,286467.000000,286467.000000,286467.000000,2.864520e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,286467.000000,286467.0,286467.0,286467.0,286467.000000,286467.000000,2.864670e+05,2.864670e+05,286467.000000,286467.000000,286467.000000,286467.000000,2.864670e+05,286467.000000,286467.000000,286467.000000,286467.000000,286467.000000,286467.000000,286467.0,286467.000000,286467.000000,286467.000000,286467.000000,286467.000000,286467.000000,286467.0,286467.0,286467.0,286467.0,286467.0,286467.0,286467.000000,286467.000000,286467.000000,2.864670e+05,286467.000000,286467.000000,286467.000000,286467.000000,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05,2.864670e+05
mean,43932.432563,8044.876324,8.306000,5.379331e+06,3.473283,3.520500,233.407667,2.707247e+03,81.033369,10.352013,24.138688,24.590994,185.649851,27.478530,76.473013,55.742307,inf,inf,3.435661e+05,6.690304e+05,1.821288e+06,1.152034e+04,5.255228e+06,7.790948e+05,5.086644e+05,1.773447e+06,4.483619e+05,4.968463e+06,7.972503e+05,3.961929e+05,1.569683e+06,5.053646e+05,0.020994,0.0,0.0,0.0,91.861527,87.156077,4.140927e+04,2.110817e+04,10.124908,206.783141,47.863395,61.756216,3.557227e+04,0.008692,0.020994,0.000073,0.660694,0.124116,0.044672,0.0,0.000073,0.850625,55.157954,24.138688,76.473013,91.861527,0.0,0.0,0.0,0.0,0.0,0.0,3.473283,233.407667,3.520500,2.707247e+03,11145.127076,1155.099977,1.728618,29.075328,3.409213e+04,2.294987e+04,7.785722e+04,2.171380e+04,1.602973e+06,6.120390e+04,1.647188e+06,1.536286e+06
std,17713.904328,15378.583442,4.481562,2.192364e+07,19.515131,28.288916,1865.523600,5.097783e+04,327.768035,24.237795,78.381542,117.218043,585.720606,54.209647,204.152865,196.643780,NaN,NaN,2.124999e+06,3.830433e+06,9.034294e+06,3.800536e+05,2.179685e+07,5.979401e+06,2.575708e+06,9.019385e+06,5.776419e+06,2.125371e+07,6.242734e+06,2.371670e+06,8.712596e+06,6.042689e+06,0.143363,0.0,0.0,0.0,503.560131,698.237440,1.601312e+05,6.246254e+04,18.768649,636.614018,122.031372,178.209296,1.631016e+05,0.092826,0.143363,0.008562,0.473475,0.329714,0.206583,0.0,0.008562,0.450208,129.794071,78.381542,204.152865,503.560131,0.0,0.0,0.0,0.0,0.0,0.0,19.515131,1865.523600,28.288916,5.097783e+04,14274.278654,6645.329412,14.897361,8.014607,4.659319e+05,2.623049e+05,7.342606e+05,4.223145e+05,8.682334e+06,1.217016e+06,8.882728e+06,8.561545e+06
min,0.000000,0.000000,0.000000,-1.300000e+01,1.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.930000e+08,-2.000000e+06,-1.300000e+01,0.000000e+00,-1.300000e+01,-1.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,0.000000,0.000000e+00,-1.000000,-1.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,37516.000000,80.000000,6.000000,4.400000e+01,1.000000,1.000000,0.000000,6.000000e+00,0.000000,0.000000,0.000000,0.000000,6.000000,6.000000,6.000000,0.000000,7.928593e+03,1.664621e+02,4.400000e+01,0.000000e+00,4.400000e+01,6.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0,24.000000,20.000000,8.374859e+01,3.291666e+01,0.000000,6.000000,2.000000,2.309401,5.333333e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.000000,3.000000,0.000000,6.000000,24.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,1.000000,6.000000e+00,237.000000,-1.000000,0.000000,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,49008.000000,1110.000000,6.000000,6.500000e+01,1.000000,1.000000,2.000000,6.000000e+00,2.000000,2.000000,2.000000,0.000000,6.000000,6.000000,6.000000,0.000000,1.250000e+05,3.076923e+04,6.100000e+01,0.000000e+00,6.500000e+01,4.400000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,0.0,40.000000,20.000000,1.562500e+04,1.408451e+04,2.000000,6.000000,3.333333,3.464102,1.200000e+01,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,1.000000,5.000000,2.000000,6.000000,40.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,2.000000,1.000000,6.000000e+00,1024.000000,0.000000,0.000000,24.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,56576.000000,6881.000000,6.000000,2.380600e+04,2.000000,2.000000,62.000000,1.150000e+02,37.000000,6.000000,34.000000,0.000000,72.000000,6.000000,66.000000,0.000000,1.904762e+05,4.545455e+04,7.986333e+03,8.602519e+01,2.368100e+04,6.300000e+01,4.000000e+00,4.000000e+00,0.000000e+00,4.000000e+00,3.000000e+00,2.000000e+00,1.666667e+00,0.000000e+00,2.000000e+00,1.000000e+00,0.000000,0.0,0.0,0.0,44.000000,40.000000,2.272727e+04,2.272727e+04,6.000000,77.000000,53.000000,19.809359,3.924107e+02,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,1.000000,67.166667,34.000000,66.000000,44.000000,0.0,0.0,0.0,0.0,0.0,0.0,2.000000,62.000000,2.000000,1.150000e+02,29200.000000,0.000000,1.000000,40.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,65535.000000,65389.000000,17.000000,1.199999e+08,3119.000000,3635.000000,232349.000000,7.150819e+06,13929.000000,1472.000000,3412.938776,3541.466551,10136.000000,1460.000000,2442.523124,2628.883261,inf,inf,9.810000e+07,8.480000e+07,1.200000e+08,9.810000e+07,1.200000e+08,1.200000e+08,8.120000e+07,1.200000e+08,1.200000e+08,1.200000e+08,1.200000e+08,8.130000e+07,1.200000e+08,1.200000e+08,1.000000,0.0,0.0,0.0,79632.000000,81288.000000,3.000000e+06,2.000000e+06,289.000000,13929.000000,1588.000000,2497.019924,6.235109e+06,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,124.000000,2068.000000,3412.938776,2442.523124,79632.000000,0.0,0.0,0.0,0.0,0.0,0.0,3119.000000,232349.000000,3635.000000,7.150819e+06,65535.000000,65535.000000,2056.000000,60.000000,1.100000e+08,7.050000e+07,1.100000e+08,1.100000e+08,1.200000e+08,7.050000e+07,1.200000e+08,1.200000e+08

In [38]:
Friday_PS.isnull().any()

#Just Flow Bytes again

Flow ID                         False
 Source IP                      False
 Source Port                    False
 Destination IP                 False
 Destination Port               False
 Protocol                       False
 Timestamp                      False
 Flow Duration                  False
 Total Fwd Packets              False
 Total Backward Packets         False
Total Length of Fwd Packets     False
 Total Length of Bwd Packets    False
 Fwd Packet Length Max          False
 Fwd Packet Length Min          False
 Fwd Packet Length Mean         False
 Fwd Packet Length Std          False
Bwd Packet Length Max           False
 Bwd Packet Length Min          False
 Bwd Packet Length Mean         False
 Bwd Packet Length Std          False
Flow Bytes/s                     True
 Flow Packets/s                 False
 Flow IAT Mean                  False
 Flow IAT Std                   False
 Flow IAT Max                   False
 Flow IAT Min                   False
Fwd IAT Total                   False
 Fwd IAT Mean                   False
 Fwd IAT Std                    False
 Fwd IAT Max                    False
 Fwd IAT Min                    False
Bwd IAT Total                   False
 Bwd IAT Mean                   False
 Bwd IAT Std                    False
 Bwd IAT Max                    False
 Bwd IAT Min                    False
Fwd PSH Flags                   False
 Bwd PSH Flags                  False
 Fwd URG Flags                  False
 Bwd URG Flags                  False
 Fwd Header Length              False
 Bwd Header Length              False
Fwd Packets/s                   False
 Bwd Packets/s                  False
 Min Packet Length              False
 Max Packet Length              False
 Packet Length Mean             False
 Packet Length Std              False
 Packet Length Variance         False
FIN Flag Count                  False
 SYN Flag Count                 False
 RST Flag Count                 False
 PSH Flag Count                 False
 ACK Flag Count                 False
 URG Flag Count                 False
 CWE Flag Count                 False
 ECE Flag Count                 False
 Down/Up Ratio                  False
 Average Packet Size            False
 Avg Fwd Segment Size           False
 Avg Bwd Segment Size           False
 Fwd Header Length.1            False
Fwd Avg Bytes/Bulk              False
 Fwd Avg Packets/Bulk           False
 Fwd Avg Bulk Rate              False
 Bwd Avg Bytes/Bulk             False
 Bwd Avg Packets/Bulk           False
Bwd Avg Bulk Rate               False
Subflow Fwd Packets             False
 Subflow Fwd Bytes              False
 Subflow Bwd Packets            False
 Subflow Bwd Bytes              False
Init_Win_bytes_forward          False
 Init_Win_bytes_backward        False
 act_data_pkt_fwd               False
 min_seg_size_forward           False
Active Mean                     False
 Active Std                     False
 Active Max                     False
 Active Min                     False
Idle Mean                       False
 Idle Std                       False
 Idle Max                       False
 Idle Min                       False
 Label                          False
dtype: bool

In [39]:
# Since there are so little missing values, we can just drop them again

print(f"Before removing missing values: {Friday_PS.shape}")
Friday_PS.dropna(inplace=True)
print(f"After removing missing values: {Friday_PS.shape}")

Before removing missing values: (286467, 85)
After removing missing values: (286452, 85)

In [40]:
Friday_PS[' Timestamp'] = pd.to_datetime(Friday_PS[' Timestamp'], format="%d/%m/%Y %H:%M")

Friday_PS.info()

<class 'pandas.DataFrame'>
Index: 286452 entries, 0 to 286466
Data columns (total 85 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Flow ID                       286452 non-null  str
 1    Source IP                    286452 non-null  str
 2    Source Port                  286452 non-null  int64
 3    Destination IP               286452 non-null  str
 4    Destination Port             286452 non-null  int64
 5    Protocol                     286452 non-null  int64
 6    Timestamp                    286452 non-null  datetime64[us]
 7    Flow Duration                286452 non-null  int64
 8    Total Fwd Packets            286452 non-null  int64
 9    Total Backward Packets       286452 non-null  int64
 10  Total Length of Fwd Packets   286452 non-null  int64
 11   Total Length of Bwd Packets  286452 non-null  int64
 12   Fwd Packet Length Max        286452 non-null  int64
 13   Fwd Packet Length Min        286452 non-null  int64
 14   Fwd Packet Length Mean       286452 non-null  float64
 15   Fwd Packet Length Std        286452 non-null  float64
 16  Bwd Packet Length Max         286452 non-null  int64
 17   Bwd Packet Length Min        286452 non-null  int64
 18   Bwd Packet Length Mean       286452 non-null  float64
 19   Bwd Packet Length Std        286452 non-null  float64
 20  Flow Bytes/s                  286452 non-null  float64
 21   Flow Packets/s               286452 non-null  float64
 22   Flow IAT Mean                286452 non-null  float64
 23   Flow IAT Std                 286452 non-null  float64
 24   Flow IAT Max                 286452 non-null  float64
 25   Flow IAT Min                 286452 non-null  float64
 26  Fwd IAT Total                 286452 non-null  float64
 27   Fwd IAT Mean                 286452 non-null  float64
 28   Fwd IAT Std                  286452 non-null  float64
 29   Fwd IAT Max                  286452 non-null  float64
 30   Fwd IAT Min                  286452 non-null  float64
 31  Bwd IAT Total                 286452 non-null  float64
 32   Bwd IAT Mean                 286452 non-null  float64
 33   Bwd IAT Std                  286452 non-null  float64
 34   Bwd IAT Max                  286452 non-null  float64
 35   Bwd IAT Min                  286452 non-null  float64
 36  Fwd PSH Flags                 286452 non-null  int64
 37   Bwd PSH Flags                286452 non-null  int64
 38   Fwd URG Flags                286452 non-null  int64
 39   Bwd URG Flags                286452 non-null  int64
 40   Fwd Header Length            286452 non-null  int64
 41   Bwd Header Length            286452 non-null  int64
 42  Fwd Packets/s                 286452 non-null  float64
 43   Bwd Packets/s                286452 non-null  float64
 44   Min Packet Length            286452 non-null  int64
 45   Max Packet Length            286452 non-null  int64
 46   Packet Length Mean           286452 non-null  float64
 47   Packet Length Std            286452 non-null  float64
 48   Packet Length Variance       286452 non-null  float64
 49  FIN Flag Count                286452 non-null  int64
 50   SYN Flag Count               286452 non-null  int64
 51   RST Flag Count               286452 non-null  int64
 52   PSH Flag Count               286452 non-null  int64
 53   ACK Flag Count               286452 non-null  int64
 54   URG Flag Count               286452 non-null  int64
 55   CWE Flag Count               286452 non-null  int64
 56   ECE Flag Count               286452 non-null  int64
 57   Down/Up Ratio                286452 non-null  int64
 58   Average Packet Size          286452 non-null  float64
 59   Avg Fwd Segment Size         286452 non-null  float64
 60   Avg Bwd Segment Size         286452 non-null  float64
 61   Fwd Header Length.1          286452 non-null  int64
 62  Fwd Avg Bytes/Bulk            286452 non-null  int64
 63   Fwd Avg Packets/Bulk         286452 non-null  int64
 64   Fwd Avg Bulk Rate            286452 non-null  int64
 65   Bwd Avg Bytes/Bulk           286452 non-null  int64
 66   Bwd Avg Packets/Bulk         286452 non-null  int64
 67  Bwd Avg Bulk Rate             286452 non-null  int64
 68  Subflow Fwd Packets           286452 non-null  int64
 69   Subflow Fwd Bytes            286452 non-null  int64
 70   Subflow Bwd Packets          286452 non-null  int64
 71   Subflow Bwd Bytes            286452 non-null  int64
 72  Init_Win_bytes_forward        286452 non-null  int64
 73   Init_Win_bytes_backward      286452 non-null  int64
 74   act_data_pkt_fwd             286452 non-null  int64
 75   min_seg_size_forward         286452 non-null  int64
 76  Active Mean                   286452 non-null  float64
 77   Active Std                   286452 non-null  float64
 78   Active Max                   286452 non-null  float64
 79   Active Min                   286452 non-null  float64
 80  Idle Mean                     286452 non-null  float64
 81   Idle Std                     286452 non-null  float64
 82   Idle Max                     286452 non-null  float64
 83   Idle Min                     286452 non-null  float64
 84   Label                        286452 non-null  str
dtypes: datetime64[us](1), float64(36), int64(44), str(4)
memory usage: 206.8 MB